INSERT INTO WATCH (brand, origin, price, category) VALUES
('Seiko', 'Japón', 250, 'Casual'),
('Rolex', 'Suiza', 5000, 'Lujo'),
('Casio', 'Japón', 100, 'Deportivo'),
('Omega', 'Suiza', 3500, 'Lujo'),
('Timex', 'EEUU', 150, 'Casual'),
('Citizen', 'Japón', 300, 'Casual'),
('Tag Heuer', 'Suiza', 2500, 'Deportivo'),
('Tissot', 'Suiza', 800, 'Casual'),
('Fossil', 'EEUU', 200, 'Casual'),
('Hamilton', 'Suiza', 1200, 'Clásico'),
('Invicta', 'EEUU', 180, 'Deportivo'),
('Bulova', 'EEUU', 400, 'Casual'),
('Longines', 'Suiza', 1800, 'Clásico'),
('G-Shock', 'Japón', 150, 'Deportivo'),
('Panerai', 'Suiza', 7000, 'Lujo'),
('Orient', 'Japón', 220, 'Casual'),
('Breitling', 'Suiza', 6000, 'Lujo'),
('Swatch', 'Suiza', 120, 'Casual'),
('Casio Vintage', 'Japón', 80, 'Retro'),
('Apple Watch', 'EEUU', 450, 'Tecnológico');
